FISHING_RARITY_TIERS = {
    "Common": {
        "items": [
            "cod",
            "salmon",
            "pufferfish",
            "tropical fish",
            "shrimp",
            "anchovy",
            "herring",
            "bluegill",
        ],
        "value_range": (50, 100),
        "weight": 60,
    },
    "Uncommon": {
        "items": [
            "clownfish",
            "swordfish",
            "piranha",
            "catfish",
            "bass",
            "snapper",
            "mackerel",
            "eel",
        ],
        "value_range": (100, 150),
        "weight": 25,
    },
    "Rare": {
        "items": [
            "enchanted book",
            "fishing rod",
            "name tag",
            "magma cream",
            "ender pearl",
            "sea lantern",
            "shell fragment",
            "ancient scale",
            "nether crab",
        ],
        "value_range": (150, 250),
        "weight": 10,
    },
    "Epic": {
        "items": [
            "treasure map",
            "nautilus shell",
            "heart of the sea",
            "ghost fish",
            "fishing lure",
            "golden scale",
            "sea serpent fang",
            "sunken crown",
        ],
        "value_range": (250, 500),
        "weight": 4,
    },
    "Legendary": {
        "items": [
            "trident",
            "enchanted golden apple",
            "dragon egg",
            "elder guardian",
            "rainbow fish",
            "kraken tentacle",
            "sunken treasure",
            "leviathan scale",
        ],
        "value_range": (1500, 2000),
        "weight": 1,
    },
}
