MINING_RARITY_TIERS = {
    "Common": {
        "items": [
            "dirt",
            "sand",
            "cobblestone",
            "wood",
            "gravel",
            "andesite",
            "granite",
            "diorite",
        ],
        "value_range": (1, 10),
        "weight": 60,
    },
    "Uncommon": {
        "items": [
            "coal",
            "redstone",
            "lapis lazuli",
            "copper",
            "tin",
            "flint",
            "charcoal",
            "clay",
        ],
        "value_range": (10, 25),
        "weight": 25,
    },
    "Rare": {
        "items": [
            "iron",
            "gold",
            "nether quartz",
            "platinum",
            "golden apple",
            "amethyst",
            "glowstone",
            "honeycomb",
            "quartz block",
        ],
        "value_range": (25, 60),
        "weight": 10,
    },
    "Epic": {
        "items": [
            "diamond",
            "emerald",
            "mythril",
            "sponge",
            "heart of the sea",
            "totem of undying",
            "prismarine shard",
            "enchanted golden apple",
        ],
        "value_range": (60, 150),
        "weight": 4,
    },
    "Legendary": {
        "items": [
            "ancient debris",
            "netherite scrap",
            "nether star",
            "dragon egg",
            "elytra",
            "beacon",
            "enchanted book",
            "dragon head",
        ],
        "value_range": (150, 500),
        "weight": 1,
    },
}

FISHING_RARITY_TIERS = {
    "Common": {
        "items": [
            "cod",
            "salmon",
            "pufferfish",
            "tropical fish",
        ],
        "value_range": (1, 10),
        "weight": 50,
    },
    "Uncommon": {
        "items": [
            "clownfish",
            "swordfish",
            "piranha",
            "catfish",
            "bass",
        ],
        "value_range": (10, 30),
        "weight": 30,
    },
    "Rare": {
        "items": [
            "enchanted book",
            "fishing rod",
            "name tag",
            "magma cream",
            "ender pearl",
        ],
        "value_range": (30, 75),
        "weight": 15,
    },
    "Epic": {
        "items": [
            "treasure map",
            "nautilus shell",
            "heart of the sea",
            "ghost fish",
            "fishing lure",
        ],
        "value_range": (75, 200),
        "weight": 4,
    },
    "Legendary": {
        "items": [
            "trident",
            "enchanted golden apple",
            "dragon egg",
            "elder guardian",
            "rainbow fish",
        ],
        "value_range": (200, 500),
        "weight": 1,
    },
}
