MINING_RARITY_TIERS = {
    "Common": {
        "items": [
            "dirt",
            "sand",
            "cobblestone",
            "wood",
            "gravel",
            "andesite",
            "granite",
            "diorite",
        ],
        "value_range": (50, 100),
        "weight": 60,
    },
    "Uncommon": {
        "items": [
            "coal",
            "redstone",
            "lapis lazuli",
            "copper",
            "tin",
            "flint",
            "charcoal",
            "clay",
        ],
        "value_range": (100, 150),
        "weight": 25,
    },
    "Rare": {
        "items": [
            "iron",
            "gold",
            "nether quartz",
            "platinum",
            "golden apple",
            "amethyst",
            "glowstone",
            "honeycomb",
            "quartz block",
        ],
        "value_range": (150, 250),
        "weight": 10,
    },
    "Epic": {
        "items": [
            "diamond",
            "emerald",
            "mythril",
            "sponge",
            "heart of the sea",
            "totem of undying",
            "prismarine shard",
            "enchanted golden apple",
        ],
        "value_range": (250, 500),
        "weight": 4,
    },
    "Legendary": {
        "items": [
            "ancient debris",
            "netherite scrap",
            "nether star",
            "dragon egg",
            "elytra",
            "beacon",
            "enchanted book",
            "dragon head",
        ],
        "value_range": (1500, 2000),
        "weight": 1,
    },
}
