SHOP_ITEMS = {
    "bank_upgrade": {
        "name": "Bank Upgrade",
        "description": "Increases your bank cap by $500,000.",
        "base_price": 500_000,
        "price_increment": 500_000,
        "effect": "bank_cap_increase",
    },
    "buffs": {
        "exp": {
            "exp_boost_50": {
                "name": "Exp Boost 50%",
                "description": "Increase your experience gained by 50% for 30 mins",
                "price": 500_000,
                "buff_type": "exp",
                "multiplier": 1.5,
                "duration": 30,
            },
            "exp_boost_100": {
                "name": "Exp Boost 100%",
                "description": "Increase your experience gained by 100% for 30 mins",
                "price": 900_000,
                "buff_type": "exp",
                "multiplier": 2.0,
                "duration": 30,
            },
        },
        "steal": {
            "lucky_day": {
                "name": "Lucky Day",
                "description": "Boosts your steal success chance by 10% for 3 hour",
                "price": 100_000,
                "buff_type": "steal_success",
                "multiplier": 1.10,
                "duration": 180,
            },
            "anti_theft_aura": {
                "name": "Anti-Theft Aura",
                "description": "Reduces chance of being stolen from by 10% for 3 hour",
                "price": 100_000,
                "buff_type": "steal_resistance",
                "multiplier": 0.9,
                "duration": 180,
            },
        },
    },
    "tools": {
        "pickaxe": {
            "wooden": {
                "name": "Wooden Pickaxe",
                "description": "Increases your mining bonus by 50%",
                "price": 10_000,
                "effect": "mining_bonus_increase",
                "level_required": 10,
                "bonus": 0.50,
            },
            "stone": {
                "name": "Stone Pickaxe",
                "description": "Increases your mining bonus by 100%",
                "price": 50_000,
                "effect": "mining_bonus_increase",
                "level_required": 20,
                "bonus": 1.00,
            },
            "copper": {
                "name": "Copper Pickaxe",
                "description": "Increases your mining bonus by 200%",
                "price": 100_000,
                "effect": "mining_bonus_increase",
                "level_required": 30,
                "bonus": 2.00,
            },
            "iron": {
                "name": "Iron Pickaxe",
                "description": "Increases your mining bonus by 400%",
                "price": 500_000,
                "effect": "mining_bonus_increase",
                "level_required": 40,
                "bonus": 4.00,
            },
            "gold": {
                "name": "Gold Pickaxe",
                "description": "Increases your mining bonus by 800%",
                "price": 1_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 50,
                "bonus": 8.00,
            },
            "diamond": {
                "name": "Diamond Pickaxe",
                "description": "Increases your mining bonus by 1600%",
                "price": 5_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 60,
                "bonus": 16.00,
            },
            "netherite": {
                "name": "Netherite Pickaxe",
                "description": "Increases your mining bonus by 3200%",
                "price": 10_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 70,
                "bonus": 32.00,
            },
        },
        "fishingrod": {
            "wooden": {
                "name": "Wooden Fishing Rod",
                "description": "Increases your fishing bonus by 50%",
                "price": 10_000,
                "effect": "fishing_bonus_increase",
                "level_required": 10,
                "bonus": 0.50,
            },
            "stone": {
                "name": "Stone Fishing Rod",
                "description": "Increases your fishing bonus by 100%",
                "price": 50_000,
                "effect": "fishing_bonus_increase",
                "level_required": 20,
                "bonus": 0.20,
            },
            "copper": {
                "name": "Copper Fishing Rod",
                "description": "Increases your fishing bonus by 200%",
                "price": 100_000,
                "effect": "fishing_bonus_increase",
                "level_required": 30,
                "bonus": 2.00,
            },
            "iron": {
                "name": "Iron Fishing Rod",
                "description": "Increases your fishing bonus by 400%",
                "price": 500_000,
                "effect": "fishing_bonus_increase",
                "level_required": 40,
                "bonus": 4.00,
            },
            "gold": {
                "name": "Gold Fishing Rod",
                "description": "Increases your fishing bonus by 800%",
                "price": 1_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 50,
                "bonus": 8.00,
            },
            "diamond": {
                "name": "Diamond Fishing Rod",
                "description": "Increases your fishing bonus by 1600%",
                "price": 5_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 60,
                "bonus": 16.00,
            },
            "netherite": {
                "name": "Netherite Fishing Rod",
                "description": "Increases your fishing bonus by 3200%",
                "price": 10_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 70,
                "bonus": 32.00,
            },
        },
    },
}
