SHOP_ITEMS = {
    "bank_upgrade": {
        "name": "Bank Upgrade",
        "description": "Increases your bank cap by $500,000.",
        "base_price": 500_000,
        "price_increment": 500_000,
        "effect": "bank_cap_increase",
    },
    "tools": {
        "pickaxe": {
            "wooden": {
                "name": "Wooden Pickaxe",
                "description": "Increases your mining bonus by 10%",
                "price": 10_000,
                "effect": "mining_bonus_increase",
                "level_required": 10,
                "bonus": 0.10,
            },
            "stone": {
                "name": "Stone Pickaxe",
                "description": "Increases your mining bonus by 20%",
                "price": 20_000,
                "effect": "mining_bonus_increase",
                "level_required": 20,
                "bonus": 0.20,
            },
            "copper": {
                "name": "Copper Pickaxe",
                "description": "Increases your mining bonus by 30%",
                "price": 40_000,
                "effect": "mining_bonus_increase",
                "level_required": 30,
                "bonus": 0.30,
            },
            "iron": {
                "name": "Iron Pickaxe",
                "description": "Increases your mining bonus by 40%",
                "price": 70_000,
                "effect": "mining_bonus_increase",
                "level_required": 40,
                "bonus": 0.40,
            },
            "gold": {
                "name": "Gold Pickaxe",
                "description": "Increases your mining bonus by 50%",
                "price": 110_000,
                "effect": "mining_bonus_increase",
                "level_required": 50,
                "bonus": 0.50,
            },
            "diamond": {
                "name": "Diamond Pickaxe",
                "description": "Increases your mining bonus by 60%",
                "price": 160_000,
                "effect": "mining_bonus_increase",
                "level_required": 60,
                "bonus": 0.60,
            },
            "netherite": {
                "name": "Netherite Pickaxe",
                "description": "Increases your mining bonus by 70%",
                "price": 220_000,
                "effect": "mining_bonus_increase",
                "level_required": 70,
                "bonus": 0.70,
            },
        },
        "fishingrod": {
            "wooden": {
                "name": "Wooden Fishing Rod",
                "description": "Increases your fishing bonus by 10%",
                "price": 10_000,
                "effect": "fishing_bonus_increase",
                "level_required": 10,
                "bonus": 0.10,
            },
            "stone": {
                "name": "Stone Fishing Rod",
                "description": "Increases your fishing bonus by 20%",
                "price": 20_000,
                "effect": "fishing_bonus_increase",
                "level_required": 20,
                "bonus": 0.20,
            },
            "copper": {
                "name": "Copper Fishing Rod",
                "description": "Increases your fishing bonus by 30%",
                "price": 40_000,
                "effect": "fishing_bonus_increase",
                "level_required": 30,
                "bonus": 0.30,
            },
            "iron": {
                "name": "Iron Fishing Rod",
                "description": "Increases your fishing bonus by 40%",
                "price": 70_000,
                "effect": "fishing_bonus_increase",
                "level_required": 40,
                "bonus": 0.40,
            },
            "gold": {
                "name": "Gold Fishing Rod",
                "description": "Increases your fishing bonus by 50%",
                "price": 110_000,
                "effect": "fishing_bonus_increase",
                "level_required": 50,
                "bonus": 0.50,
            },
            "diamond": {
                "name": "Diamond Fishing Rod",
                "description": "Increases your fishing bonus by 60%",
                "price": 160_000,
                "effect": "fishing_bonus_increase",
                "level_required": 60,
                "bonus": 0.60,
            },
            "netherite": {
                "name": "Netherite Fishing Rod",
                "description": "Increases your fishing bonus by 70%",
                "price": 220_000,
                "effect": "fishing_bonus_increase",
                "level_required": 70,
                "bonus": 0.70,
            },
        },
    },
}
