SHOP_ITEMS = {
    "bank_upgrade": {
        "name": "Bank Upgrade",
        "description": "Increases your bank cap by $500,000.",
        "base_price": 500_000,
        "price_increment": 500_000,
        "effect": "bank_cap_increase",
    },
    "tools": {
        "pickaxe": {
            "wooden": {
                "name": "Wooden Pickaxe",
                "description": "Increases your mining bonus by 10%",
                "price": 10_000,
                "effect": "mining_bonus_increase",
                "level_required": 10,
                "bonus": 0.10,
            },
            "stone": {
                "name": "Stone Pickaxe",
                "description": "Increases your mining bonus by 20%",
                "price": 50_000,
                "effect": "mining_bonus_increase",
                "level_required": 20,
                "bonus": 0.20,
            },
            "copper": {
                "name": "Copper Pickaxe",
                "description": "Increases your mining bonus by 40%",
                "price": 100_000,
                "effect": "mining_bonus_increase",
                "level_required": 30,
                "bonus": 0.40,
            },
            "iron": {
                "name": "Iron Pickaxe",
                "description": "Increases your mining bonus by 80%",
                "price": 500_000,
                "effect": "mining_bonus_increase",
                "level_required": 40,
                "bonus": 0.80,
            },
            "gold": {
                "name": "Gold Pickaxe",
                "description": "Increases your mining bonus by 160%",
                "price": 1_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 50,
                "bonus": 1.60,
            },
            "diamond": {
                "name": "Diamond Pickaxe",
                "description": "Increases your mining bonus by 320%",
                "price": 5_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 60,
                "bonus": 3.20,
            },
            "netherite": {
                "name": "Netherite Pickaxe",
                "description": "Increases your mining bonus by 640%",
                "price": 10_000_000,
                "effect": "mining_bonus_increase",
                "level_required": 70,
                "bonus": 6.40,
            },
        },
        "fishingrod": {
            "wooden": {
                "name": "Wooden Fishing Rod",
                "description": "Increases your fishing bonus by 10%",
                "price": 10_000,
                "effect": "fishing_bonus_increase",
                "level_required": 10,
                "bonus": 0.10,
            },
            "stone": {
                "name": "Stone Fishing Rod",
                "description": "Increases your fishing bonus by 20%",
                "price": 50_000,
                "effect": "fishing_bonus_increase",
                "level_required": 20,
                "bonus": 0.20,
            },
            "copper": {
                "name": "Copper Fishing Rod",
                "description": "Increases your fishing bonus by 40%",
                "price": 100_000,
                "effect": "fishing_bonus_increase",
                "level_required": 30,
                "bonus": 0.40,
            },
            "iron": {
                "name": "Iron Fishing Rod",
                "description": "Increases your fishing bonus by 80%",
                "price": 500_000,
                "effect": "fishing_bonus_increase",
                "level_required": 40,
                "bonus": 0.80,
            },
            "gold": {
                "name": "Gold Fishing Rod",
                "description": "Increases your fishing bonus by 160%",
                "price": 1_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 50,
                "bonus": 1.60,
            },
            "diamond": {
                "name": "Diamond Fishing Rod",
                "description": "Increases your fishing bonus by 320%",
                "price": 5_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 60,
                "bonus": 3.20,
            },
            "netherite": {
                "name": "Netherite Fishing Rod",
                "description": "Increases your fishing bonus by 640%",
                "price": 10_000_000,
                "effect": "fishing_bonus_increase",
                "level_required": 70,
                "bonus": 6.40,
            },
        },
    },
}
